name: Frontend CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'frontend/**'
      - '.github/workflows/actions_frontend.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'frontend/**'
      - '.github/workflows/actions_frontend.yml'

jobs:
   build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run : npm ci
        working-directory: frontend

      - name: Run Linter
        run: npm run lint
        working-directory: frontend

      - name: Build Frontend
        run: npm run build
        working-directory: frontend

      - name: Build Docker Image
        run: docker build -t core-banking-frontend:latest .
        working-directory: frontend
